// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  source_id: string;
  path?: string;
  seo_title?: string;
  seo_description?: string;
  content?: PortableTextBlock[];
  data?: unknown;
  baseline_hash?: string;
  source_payload_hash?: string;
  base_manifest_hash?: string;
  source_updated_at?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface PagesCommerciale {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  source_id: string;
  path?: string;
  seo_title?: string;
  seo_description?: string;
  content?: PortableTextBlock[];
  data?: unknown;
  baseline_hash?: string;
  source_payload_hash?: string;
  base_manifest_hash?: string;
  source_updated_at?: string;
  service?: "site" | "automation" | "application";
  department_code?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Realisation {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  source_id: string;
  path?: string;
  seo_title?: string;
  seo_description?: string;
  content?: PortableTextBlock[];
  data?: unknown;
  baseline_hash?: string;
  source_payload_hash?: string;
  base_manifest_hash?: string;
  source_updated_at?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Guide {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  source_id: string;
  path?: string;
  seo_title?: string;
  seo_description?: string;
  content?: PortableTextBlock[];
  data?: unknown;
  baseline_hash?: string;
  source_payload_hash?: string;
  base_manifest_hash?: string;
  source_updated_at?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Commune {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  source_id: string;
  path?: string;
  seo_title?: string;
  seo_description?: string;
  content?: PortableTextBlock[];
  data?: unknown;
  baseline_hash?: string;
  source_payload_hash?: string;
  base_manifest_hash?: string;
  source_updated_at?: string;
  commune_code?: string;
  department_code?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface FichesTerritoriale {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  source_id: string;
  path?: string;
  seo_title?: string;
  seo_description?: string;
  content?: PortableTextBlock[];
  data?: unknown;
  baseline_hash?: string;
  source_payload_hash?: string;
  base_manifest_hash?: string;
  source_updated_at?: string;
  commune_code?: string;
  department_code?: string;
  axis?: "sites" | "automatisation";
  editorial_status?: "prepared-not-editorially-approved" | "reviewed";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    pages_commerciales: PagesCommerciale;
    realisations: Realisation;
    guides: Guide;
    communes: Commune;
    fiches_territoriales: FichesTerritoriale;
  }
}