import {test} from 'node:test';
import assert from 'node:assert/strict';
import {extractPage,applyPage,hash,safeLink,renderBlockBody} from './content.mjs';
const html='<!doctype html><html><head><title>Un projet</title><meta name="description" content="Description"><meta property="og:title" content="Un projet"><link rel="canonical" href="https://flex-web.fr/test/"><script type="application/ld+json">{"@type":"WebPage","name":"Un projet","description":"Description"}</script></head><body><nav>Non éditable</nav><main><header><h1>Votre projet</h1></header><p>Un texte avec <strong>une preuve</strong>.</p><p>Le prix : 299 € TTC.</p><form><input name="email"><button>Envoyer</button></form><astro-island><p>Élément interactif</p></astro-island><script>window.safe=true</script></main><footer>Contact</footer></body></html>';
function entry(){const p=extractPage(html,'/test/');return {collection:'pages',path:'/test/',content:structuredClone(p.content),seoTitle:p.title,seoDescription:p.description,data:{renderHash:p.renderHash,additionalSections:[]}};}
test('source extraction includes hero and preserves islands, forms and scripts',()=>{const e=entry();assert.equal(e.content.length,3);assert.equal(applyPage(html,e),html);assert.match(JSON.stringify(e.content),/Votre projet/);assert.doesNotMatch(JSON.stringify(e.content),/interactif|window.safe|Non éditable/);});
test('editable text is escaped while interactive HTML remains byte-for-byte unchanged',()=>{const e=entry();e.content[1].children[0].text='<script>mauvais</script> ';const output=applyPage(html,e);assert.match(output,/&lt;script&gt;mauvais/);assert.match(output,/<form><input name="email"><button>Envoyer<\/button><\/form>/);assert.match(output,/<astro-island><p>Élément interactif/);});
test('current source fingerprint is mandatory',()=>{const e=entry();assert.throws(()=>applyPage(html.replace('une preuve','deux preuves'),e),/source modifié/);});
test('catalogue amounts cannot be silently changed via rich text',()=>{const e=entry();e.content[2].children[0].text='Le prix : 199 € TTC.';assert.throws(()=>applyPage(html,e),/catalogue/);});
test('missing, repeated and foreign blocks fail closed',()=>{for(const change of [e=>e.content.pop(),e=>e.content.push(e.content[0]),e=>e.content[0]._key='new']){const e=entry();change(e);assert.throws(()=>applyPage(html,e));}});
test('metadata and associated structured data stay consistent',()=>{const e=entry();e.seoTitle='Titre <clair>';e.seoDescription='Une description utile';const output=applyPage(html,e);assert.match(output,/<title>Titre &lt;clair&gt;<\/title>/);assert.match(output,/property="og:title" content="Titre &lt;clair&gt;"/);assert.match(output,/"name":"Titre \\u003cclair>"/);assert.match(output,/"description":"Une description utile"/);});
test('dangerous links and quote injection rejected or escaped',()=>{for(const href of ['javascript:alert(1)','data:text/html,x','//evil.test','/\\evil.test','https://u:p@test.test/'])assert.throws(()=>safeLink(href));assert.equal(safeLink('/demarrer/?service=site'),'/demarrer/?service=site');const b={_type:'block',children:[{_type:'span',text:'Devis',marks:['x']}],markDefs:[{_key:'x',_type:'link',href:'https://example.test/"x'}]};assert.match(renderBlockBody(b),/&quot;/);});
test('additional sections do not execute HTML and never change historical prices',()=>{const e=entry();e.data.additionalSections=[{title:'Une preuve',text:'<img src=x onerror=alert(1)>'}];assert.match(applyPage(html,e),/&lt;img/);e.data.additionalSections[0].text='Une offre à 100 €';assert.throws(()=>applyPage(html,e),/catalogue/);});
test('national guides require a review that matches this exact content',()=>{const e=entry();e.path='/ressources/sites/test/';e.collection='guides';const h=html.replace('https://flex-web.fr/test/','https://flex-web.fr/ressources/sites/test/');assert.throws(()=>applyPage(h,e),/relecture/);e.data.editorialReview={reviewer:'Relecture de test',reviewedAt:'2026-09-30T00:00:00Z',hash:hash({content:e.content,seoTitle:e.seoTitle,seoDescription:e.seoDescription,additionalSections:[]})};assert.equal(applyPage(h,e),h);e.content[0].children[0].text='Modifié';assert.throws(()=>applyPage(h,e),/relecture/);});
