import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { canonical, hash, sameSecret, contentPayload, snapshotId, validateSnapshot, nextStatus, toEntry } from '../src/lib/contracts.mjs';

const entry = { collection: 'pages', sourceId: 'home', path: '/', title: 'Accueil', seoTitle: 'Flex-Web', seoDescription: 'Des sites utiles', content: [{ _type: 'block', _key: 'hero', children: [{ _type: 'span', _key: 'text', text: 'Un site utile', marks: [] }] }], data: { template: 'home' }, revision: '1', updatedAt: '2026-09-30T08:00:00.000Z' };
const createSnapshot = () => { const s = { schemaVersion: 1, createdAt: '2026-09-30T08:00:00.000Z', sourceCommit: 'a'.repeat(40), entries: [entry], pricingFingerprint: 'b'.repeat(64), baseManifestHash: 'c'.repeat(64) }; return { ...s, id: snapshotId(s) }; };
test('canonical hash preserves array order but ignores object key order', () => { assert.equal(hash({ b: 2, a: 1 }), hash({ a: 1, b: 2 })); assert.notEqual(hash([1, 2]), hash([2, 1])); });
test('secrets fail closed and require at least 32 characters', () => { assert.equal(sameSecret('', ''), false); assert.equal(sameSecret('short', 'short'), false); assert.equal(sameSecret('x'.repeat(32), 'x'.repeat(32)), true); assert.equal(sameSecret('y'.repeat(32), 'x'.repeat(32)), false); });
test('snapshot id survives retry time changes but rejects edited content', () => { const s = createSnapshot(); validateSnapshot(s); assert.equal(snapshotId({ ...s, createdAt: '2026-10-01T00:00:00.000Z' }), s.id); assert.throws(() => validateSnapshot({ ...s, entries: [{ ...entry, title: 'Changed' }] }), /INVALID_SNAPSHOT_ID/); });
test('snapshot rejects unknown collections, duplicate identifiers and unsafe paths', () => { for (const entries of [[{ ...entry, collection: 'users' }], [entry, entry], [{ ...entry, path: '//evil.example/' }]]) { const s = { ...createSnapshot(), entries }; s.id = snapshotId(s); assert.throws(() => validateSnapshot(s)); } });
test('live field mapping separates content from structured data and computes baseline', () => { const fields = { source_id: 'home', path: '/', title: entry.title, seo_title: entry.seoTitle, seo_description: entry.seoDescription, content: entry.content, data: entry.data }; assert.deepEqual(contentPayload(fields), { title: entry.title, seoTitle: entry.seoTitle, seoDescription: entry.seoDescription, content: entry.content, data: entry.data }); assert.equal(toEntry('pages', { data: fields, version: 3, updatedAt: entry.updatedAt }).revision, '3'); });
test('release states enforce checks and idempotency', () => { const draft = { id: 'x', state: 'draft', updatedAt: entry.updatedAt }; assert.throws(() => nextStatus(draft, { state: 'deployed', expectedState: 'draft', deployId: 'deployment123' }), /STATE_CONFLICT/); const checking = nextStatus(draft, { state: 'checking', expectedState: 'draft' }); assert.equal(nextStatus(checking, { state: 'checking', expectedState: 'draft' }), checking); const preview = nextStatus(checking, { state: 'preview_ready', expectedState: 'checking', previewUrl: 'https://deploy-preview-1--flex-webb.netlify.app/' }); assert.throws(() => nextStatus(preview, { state: 'deployed', expectedState: 'checking', deployId: 'deployment123' }), /STATE_CONFLICT/); assert.equal(nextStatus(preview, { state: 'deployed', expectedState: 'preview_ready', deployId: 'deployment123' }).state, 'deployed'); });
test('schema has all six collections, stable ids and revision support without sample content', () => { const seed = JSON.parse(readFileSync(new URL('../seed/seed.json', import.meta.url))); assert.equal(seed.collections.length, 6); assert.deepEqual(seed.content, {}); for (const collection of seed.collections) { assert.ok(collection.supports.includes('revisions')); assert.ok(collection.fields.find((f) => f.slug === 'source_id' && f.unique && f.indexed)); assert.ok(collection.fields.find((f) => f.slug === 'content' && f.type === 'portableText')); } });
test('verified preview can be rechecked and a confirmed rollback can be recorded', () => { const preview = { id: 'x', state: 'preview_ready', updatedAt: entry.updatedAt }; assert.equal(nextStatus(preview, { state: 'checking', expectedState: 'preview_ready' }).state, 'checking'); const deployed = { id: 'x', state: 'deployed', deployId: 'deployment123', updatedAt: entry.updatedAt }; assert.equal(nextStatus(deployed, { state: 'review_failed', expectedState: 'deployed', errors: ['Déploiement annulé et version précédente rétablie.'] }).state, 'review_failed'); });
